### ISSUE TITLE
Feature Request: Ability to use make_munki_mpkg_DEP.sh

### ISSUE THREAD

**Issue by erikng** [ox-it/munki-rebrand#11]
There was a conversation about this feature [here](https://github.com/munki/munki/issues/687) and as of this [commit](https://github.com/munki/munki/commit/0de8f061a8d678b96fba8ef224aa66fd5df1179b) it is now merged. I have not had time to document it, but it would be helpful for people who are building alternative packages to be able to utilize this feature.

**Comment by fuzzylogiq** [comment]
Merged in #12, thanks Erik!
