### ISSUE TITLE
Munki 3.1 does not work

### ISSUE THREAD

**Issue by o-jans** [ox-it/munki-rebrand#16]
Munki-Rebrand does not work with Munki 3.1 (no problems with Munki 3.0.3):

Building customized Munki...
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Localize build/Managed\ Software\ Center.build/Release/Managed\ Software\ Center.build/Script-C09CE1D918BEA41000B9724A.sh
(1 failure)

Cleaning up...

**Comment by fuzzylogiq** [comment]
Check the README:

> It is important to open and run any newly installed version of Xcode and ensure its additional components are installed before trying to run munki-rebrand, or the build may fail.

**Comment by o-jans** [comment]
I did open and run Xcode. Still the same error with Munki 3.1 and no error with Munki 3.0.3.

**Comment by fuzzylogiq** [comment]
Please can you give some more information about your setup:

Exact command line of munki_rebrand used
Verbose output of munki_rebrand
OS Version
Xcode version

This error has only occurred in testing when Xcode 9 was installed but the additional components were not.

**Comment by o-jans** [comment]
macOS 10.12.6 (16G29)
Xcode 7.2.1 (7C1002)

$ sudo ./munki_rebrand.py --appname "Testname" --localized --munki-release v3.1.0
Password:
Cloning git repo...
Checking out tag v3.1.0
Replacing Managed Software Center with Testname in apps...
Replacing localized app names with Testname...
Building customized Munki...
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Localize build/Managed\ Software\ Center.build/Release/Managed\ Software\ Center.build/Script-C09CE1D918BEA41000B9724A.sh
(1 failure)

Cleaning up...
Done.

**Comment by fuzzylogiq** [comment]
OK it's possible that older versions of Xcode do not work with munki 3.1 - is there any reason why you cannot use Xcode 8/9? I can test this but it will take some time

**Comment by o-jans** [comment]
At the moment I need to stay with Xcode 7 but I installed a VM with Xcode 9.
It does work with Munki 3.1. Thank you!
