### ISSUE TITLE
-appname doesnt work

### ISSUE THREAD

**Issue by salihzett** [ox-it/munki-rebrand#17]
When I try to make an munki rebrand pkg, the name of the app doenst change.

```
sudo ./munki_rebrand.py -a "Custom AppStore"
Cloning git repo...
Using latest Github code...
Replacing Managed Software Center with Custom AppStore in apps...
Building customized Munki...
Customized package built at /Users/foo/git/munki-rebrand/munkitools-3.1.0.3437.pkg.
Cleaning up...
Done.
```

If i install the new package, the name is "Geführte Softwareaktuallisierung" die German version of Managed Software Center.

The possibility to change the icon works great, only the name doenst change.

Any ideas?

**Comment by fuzzylogiq** [comment]
Please consult the README. -a/--appname ONLY works for the US English app name. If you want to translate other localizations (e.g. German) you need to use the --l/--localized option.
