### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by o-jans** [ox-it/munki-rebrand#19]
Happy new year fuzzylogiq.
Glad to see that Xcode is no longer required.
Unfortunately 2.0 does not work with (german) special characters like 'ü'.
Example:

munki-rebrand-2.0 $ sudo ./munki_rebrand.py --appname "Name"
Downloading munkitools from https://github.com/munki/munki/releases/download/v3.1.1/munkitools-3.1.1.3447.pkg...
Building output pkg at /Users/user/Documents/munki-rebrand-2.0/munkitools-3.1.1.3447.pkg...
Cleaning up...
Done.

munki-rebrand-2.0 $ sudo ./munki_rebrand.py --appname "Nüme"
Downloading munkitools from https://github.com/munki/munki/releases/download/v3.1.1/munkitools-3.1.1.3447.pkg...
Traceback (most recent call last):
  File "./munki_rebrand.py", line 427, in <module>
    main()
  File "./munki_rebrand.py", line 380, in main
    replace_strings(lfile, code, args.appname)
  File "./munki_rebrand.py", line 213, in replace_strings
    right = right.replace(localized, appname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Cleaning up...
Done.

**Comment by fuzzylogiq** [comment]
Happy New year @o-jans!

Can you try checking out the unicode-fix branch i.e. `git checkout unicode-fix` and see if that fixes it for you?

**Comment by o-jans** [comment]
The unicode-fix branch fixes it for me. Thank you for your very much appreciated support.
