### ISSUE TITLE
Managed Software Center 10_6.icns

### ISSUE THREAD

**Issue by sphen13** [ox-it/munki-rebrand#21]
There appears to be a 10_6 version of the icns file within "Managed Software Center".  I know I don't really care about it nor should any good macadmin be using 10.6 still - but thought I would share and document. :)

![screen shot 2018-01-18 at 11 38 06 am](https://user-images.githubusercontent.com/524607/35109430-590259d0-fc44-11e7-9b19-618030dbdc17.png)

**Comment by fuzzylogiq** [comment]
I'm not intending to fix this. PRs welcome! :)
