### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by o-jans** [ox-it/munki-rebrand#28]
Hi fuzzylogiq, nice to see an updated version. But munki-rebrand 3.0 does not work with special characters like 'ü'.
Example:

sudo ./munki_rebrand.py --appname "Name"
Downloading munkitools from https://github.com/munki/munki/releases/download/v3.6.0/munkitools-3.6.0.3733.pkg...
Replacing app name with Name...
Building output pkg at /Users/name/Documents/munki-rebrand-3.0/munkitools-3.6.0.3721.pkg...
Cleaning up...
Done.

sudo ./munki_rebrand.py --appname "Nüme"
Downloading munkitools from https://github.com/munki/munki/releases/download/v3.6.0/munkitools-3.6.0.3733.pkg...
Replacing app name with Nüme...
Traceback (most recent call last):
  File "./munki_rebrand.py", line 518, in <module>
    main()
  File "./munki_rebrand.py", line 456, in main
    replace_strings(lfile, code, args.appname)
  File "./munki_rebrand.py", line 239, in replace_strings
    fw.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 23: ordinal not in range(128)
Cleaning up...
Done.

**Comment by fuzzylogiq** [comment]
Please try the fix in this branch:

https://github.com/ox-it/munki-rebrand/tree/unicode-fix

**Comment by o-jans** [comment]
The fix is working. Thanks.
