### ISSUE TITLE
Version number doesn't match original package

### ISSUE THREAD

**Issue by anewhouse** [ox-it/munki-rebrand#30]
The current Munki release version is 3.6.0.3734. The subpackages are:

munkitools_core-3.6.0.3721.pkg
munkitools_app_usage-3.6.0.3721.pkg
munkitools_admin-3.6.0.3721.pkg
munkitools_app-5.1.0.3734.pkg
munkitools_launchd-3.0.3265.pkg

When you use munki-rebrand, it names the package munkitools-3.6.0.3721.pkg. The official build takes the highest last number out of all the subpackages, so munki-rebrand should be using 3734 as the last part of the version number.

**Comment by fuzzylogiq** [comment]
Hi yup I've known about this for a while now - it should be using whatever munki itself uses in the build script to determine the version of the mpkg. I'll try to address it soon.

**Comment by fuzzylogiq** [comment]
This should finally be fixed in https://github.com/ox-it/munki-rebrand/tree/v4.0 which will be merged into main shortly
