### ISSUE TITLE
Error when replacing icon

### ISSUE THREAD

**Issue by silentArtifact** [ox-it/munki-rebrand#31]
When attempting to replace the app icon for the Managed Software Center, munki_rebrand throws this error:

```
Replacing icons in /tmp/tmpTuOMUq/payload/Applications/Managed Software Center.app/Contents/Resources/AppIcon.icns with /Users/Shared/munki_installer/ISU_Seal.icns...
Traceback (most recent call last):
  File "./munki_rebrand.py", line 518, in <module>
    main()
  File "./munki_rebrand.py", line 471, in main
    if car:
UnboundLocalError: local variable 'car' referenced before assignment
```

Works fine as long as I'm not attempting to change the icon.

**Comment by bochoven** [comment]
You need to supply a png file instead of a .icns file

**Comment by bochoven** [comment]
From the README: “The --icon-file option allows you to specify the path to an icon to replace the one in Managed Software Center. This must be a 1024x1024 .png file with alpha channel for transparency that will be converted on the fly.”

**Comment by fuzzylogiq** [comment]
Yes this changed with munki moving to a more modern way of dealing with icon assets in Xcode. I’ll see if I can make that error message a bit more descriptive though.

--
Ben Goodstein
Technical Leader (Apple)
________________________________

**Comment by silentArtifact** [comment]
I've converted my icon to a PNG, but it looks like I'm getting a new error:

```
Converting .png file to .icns...
xcode-select: error: tool 'actool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by fuzzylogiq** [comment]
please read the README!

**Comment by silentArtifact** [comment]
Ah, sorry. I'd googled the error and ran a few different things, I didn't anticipate the error'd be in the docs. Thanks for the help!
