### ISSUE TITLE
'actool' requires Xcode while Converting .png file to .icns error

### ISSUE THREAD

**Issue by HaniAlshikh** [ox-it/munki-rebrand#33]
Hi,

when i ran:

```bash
sudo python munki_rebrand.py --appname $appname --icon-file $icon --output-file $appname --pkg $pkg_path
```

i had this issue

```bash
Converting .png file to .icns...
xcode-select: error: tool 'actool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
and i did a quick google search and found the solution [here|https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786]

```bash
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

I hope it helps :).

**Comment by fuzzylogiq** [comment]
It’s already in the README :>

--
Ben Goodstein
Technical Leader (Apple)
________________________________

**Comment by HaniAlshikh** [comment]
Oh, sorry XD. we can close this then :).
