### ISSUE TITLE
MunkiStatus not rebranding in US English (was macOS 10.14.6 & munkitools 3.6.2 not showing icon in GUI or MunkiStatus)

### ISSUE THREAD

**Issue by apizz** [ox-it/munki-rebrand#34]
Using the most recently version of the script, ran the following from the command line:

`sudo ~/Documents/GitHub/munki-rebrand/munki_rebrand.py --appname "MYORG Auto-Update" --pkg /Users/MYUSER/Downloads/munkitools-3.6.2.3776.pkg --icon-file "/Users/MYUSER/Downloads/OURORGICON.png" --sign-package "Developer ID Installer: OURORG (OURTEAMID)"`

When installed on a machine running 10.14.6, I can see that Managed Software Center is correctly named with the specified `--appname`.  However, despite using our custom icon the app icon is still the standard MSC icon.  I can see our icon in ./Contents/Resources/AppIcon.icns and using Suspicious Package confirm it's what it should be.  Likewise, I see this icon in MunkiStatus as well, but the icon is also still the standard MSC icon.

![Screen Shot 2019-07-30 at 4 37 29 PM](https://user-images.githubusercontent.com/11789931/62164126-d90ad280-b2e9-11e9-8c76-697f666cc81b.png)
![Screen Shot 2019-07-30 at 4 37 54 PM](https://user-images.githubusercontent.com/11789931/62164156-e7f18500-b2e9-11e9-8883-6d3581dc7a09.png)
![Screen Shot 2019-07-30 at 4 38 10 PM](https://user-images.githubusercontent.com/11789931/62164177-efb12980-b2e9-11e9-9091-af566661c131.png)

More problematic is that at the loginwindow when MunkiStatus it runs, it shows the MSC icon and is titled "Managed Software Update" instead of our specified `--appname`.

![LWScreenShot 2019-07-30 at 4 39 20 PM](https://user-images.githubusercontent.com/11789931/62164183-f344b080-b2e9-11e9-8055-da06ff3a26a7.png)

The Mac I used to build this is still on 10.12.6 (am going to try another machine on a more recent OS) and Xcode 9.2, and am not sure if this is contributing to the issues here.  Wanted to report before I did additional testing.

**Comment by apizz** [comment]
New rebrand build on 10.14.6 machine with Xcode 10.13 installed caused both MSC and MunkiStatus to reflect the desired image.  However, at the loginwindow, MunkiStatus is still listed as "Managed Software Center" rather than "OURORG Auto-Update" despite the app correctly reflecting this name.

![Screen Shot 2019-08-01 at 3 25 31 PM](https://user-images.githubusercontent.com/11789931/62321841-9d9b1000-b471-11e9-9a3f-07b3fa7a48cc.png)
![Screen Shot 2019-08-01 at 3 25 42 PM](https://user-images.githubusercontent.com/11789931/62321789-76dcd980-b471-11e9-9ba0-e24a052b21e7.png)
![LWScreenShot 2019-08-01 at 3 26 12 PM](https://user-images.githubusercontent.com/11789931/62321796-7b08f700-b471-11e9-93ad-510fd67d0669.png)

**Comment by fuzzylogiq** [comment]
Well, the README does state you need XCode 10+...

As for the munkistatus bug I’ve noticed this too and will look into it when I get a chance.

--
Ben Goodstein
Technical Leader (Apple)
________________________________

**Comment by apizz** [comment]
Yeah @fuzzylogiq I saw the reqs late ... my bad on not RTFM.  Glad that you're seeing the munkistatus issue though.

**Comment by apizz** [comment]
Any updates?

**Comment by apizz** [comment]
Curious if there's any updates here?

**Comment by TSPARR** [comment]
So this seems to have been introduced in v3.6. From that point on, `en.lproj` at MunkiStatus.app/Contents/Resources/ no longer has the Localizable.strings and MainMenu.strings files, just the InfoPlist.strings file. If you change your region to somewhere else, it displays correctly. 

I'm not sure if this is something that Munki Rebrand should be accounting for or if this is something that should be taken up with on the core Munki project.

**Comment by fuzzylogiq** [comment]
Yup this is a problem upstream with localisation introduces in the move to Swift I think, and it’s fixable if I get some changes merged into munki - not had much time for this of late but will look into it very soon.

--
Ben Goodstein
Technical Leader (Apple)
________________________________

**Comment by fuzzylogiq** [comment]
Can you try the latest code in master? I've added Base.lproj to the localisations altered - not sure this is the best approach but I think it works...

**Comment by apizz** [comment]
I will try it as soon as I can.  Thank you!

**Comment by TSPARR** [comment]
Coming back to this pretty late, but confirming that the current code in master does solve the issue.

**Comment by apizz** [comment]
Sorry, this fell off my radar.  I'll list this as closed.
