### ISSUE TITLE
Adding support for notarization 

### ISSUE THREAD

**Issue by lifeunexpected** [ox-it/munki-rebrand#36]
Hey are you planning to add support for notarization like the original Munki did a few weeks ago :)?

Here is what they added to the code to make it possible.
https://github.com/munki/munki/pull/939

Thank you so much for you great work 👍

**Comment by fuzzylogiq** [comment]
addressed by https://github.com/ox-it/munki-rebrand/commit/a948d553f5ba92b351e1c1383fe89adf72cc15c6
