### ISSUE TITLE
Recommend updating the tag

### ISSUE THREAD

**Issue by clburlison** [ox-it/munki-rebrand#4]
Tag version 2.2.4 is _super_ old, your code references it [here](https://github.com/ox-it/munki-rebrand/blob/e07d6001326756ce9bc36d10c7e43b0244e45a80/munki_rebrand.py#L42-L43). Greg made a change with https://github.com/munki/munki/commit/6ad90669336e66970efa62cc5641988b5c835380 that is in  tags v2.5.0 and greater that removes the macosx10.8 sdk requirement.

At minimum I'd recommend bumping the tag version to 2.5.0, however in reality it might just be easier to set the current release of v2.8.2.

This will solve the:

``` bash
error: There is no SDK with the name or path '/Users/username/Source/munki_rebrand/munki/code/apps/Managed Software Center/macosx10.8'
```

error that @ jimmynyc had in the MacAdmin's Slack group. reference link https://macadmins.slack.com/archives/munki/p1477491267006752

This will means new users can download Xcode, accept the license agreement, download the munki-rebrand script and just go.

**Comment by fuzzylogiq** [comment]
Closing this as I believe the new script's help/README to be sufficient
