### ISSUE TITLE
postinstall.sh is not integrated

### ISSUE THREAD

**Issue by dannykorpan** [ox-it/munki-rebrand#40]
Hi,

I've tried to integrate a postinstall.sh via the p parameter. But after creating the new package with munki_rebrand.py and executing the new package or after extracting the newly created package via pkgutil --expand there is no postinstall in the package inside.

`sudo ./munki_rebrand.py -a 'Software Center' -k munkitools-4.0.0.3881.pkg -o youknow -p 'postinstall.sh'`

content of postinstall.sh
```
#!/bin/bash
SETPREF="defaults write /Library/Preferences/ManagedInstalls"
$SETPREF SoftwareRepoURL https://munki.mydomain.com
$SETPREF ClientIdentifier selfservice
```

Kind Regards

**Comment by sphen13** [comment]
Try naming it just `postinstall` without the .sh

**Comment by fuzzylogiq** [comment]
The postinstall is in the munkitools_app pkg inside the munkitools metapkg, not the metapkg itself. Where were you looking for it?

**Comment by dannykorpan** [comment]
It's now working - I don't know why it's not working in the past, because I've nothing changed.
