### ISSUE TITLE
Notarization issues

### ISSUE THREAD

**Issue by somethingavailable** [ox-it/munki-rebrand#42]
This script is very helpful in the process of distribute Munki. I have however never been able to successfully notarize the pkg even with --sign-binaries and --sign-package

Log shows ex:
 {
      "severity": "error",
      "code": null,
      "path": "Munki-employees-city-v1_2-4.1.4.3949.pkg/munkitools_python-3.7.4.pkg Contents/Payload/usr/local/munki/Python.framework/Versions/3.7/Python",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Munki-employees-city-v1_2-4.1.4.3949.pkg/munkitools_python-3.7.4.pkg Contents/Payload/usr/local/munki/Python.framework/Versions/3.7/Python",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Munki-employees-city-v1_2-4.1.4.3949.pkg/munkitools_python-3.7.4.pkg Contents/Payload/usr/local/munki/Python.framework/Versions/3.7/bin/python3.7m",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },

This one does successfully notarize: https://github.com/lifeunexpected/Scripts/blob/master/MunkiPythonNotarizeAndSign.zsh

Any tips on how to get the Munki-rebrand to successfully notarize with all binaries signed correctly?

Run command: sudo python ./munki_rebrand.py --appname Programvaresenter --sign-package Developer ID Installer: Firstname LastName (Developerid) --sign-binaries Developer ID Application: Firstname Lastname (Developerid) -p munki-city-employees.sh --output-file ./versjon_1_2/Munki-employees-city-v1_2

payload-script:
#!/bin/sh
sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://munki.organization.no/munki_repo"
sudo defaults write /Library/Preferences/ManagedInstalls ClientIdentifier City-Employees

**Comment by fuzzylogiq** [comment]
Hi the script cannot currently sign the Python binaries and it’s a lot of work for me to add this functionality, since it involves expanding a package the script has never been involved with before, and I personally have no need for notarisation. I’d happily look at PRs but I’m not able to work on this right now.

--
Ben Goodstein
Technical Leader (Apple)
________________________________

**Comment by sphen13** [comment]
I would say this is out of those scope of this tool. You can feed your own munki pkg into the rebrand script that already has signed python however and it should work. See this as example: https://github.com/lifeunexpected/munki/blob/9591fe800b4aaf1691578405300af066ae77190d/code/tools/MunkiPythonNotarizeAndSign.sh
