### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by o-jans** [ox-it/munki-rebrand#44]
Hi, munki-rebrand 3.3 does not work with special characters like 'ü'.

Example:

sudo ./munki_rebrand.py --appname "Nüme"
Downloading munkitools from https://github.com/munki/munki/releases/download/v5.1.0/munkitools-5.1.0.4107.pkg...
Replacing app name with Nüme...
Traceback (most recent call last):
  File "./munki_rebrand.py", line 622, in <module>
    main()
  File "./munki_rebrand.py", line 544, in main
    replace_strings(lfile, code, args.appname)
  File "./munki_rebrand.py", line 251, in replace_strings
    right = right.replace(localized, appname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Cleaning up...
Done.

**Comment by fuzzylogiq** [comment]
I'm sorry that this is taking so long - keeping Py2 & Py3 compatibility while working with unicode is hard.

**Comment by o-jans** [comment]
@fuzzylogiq is a fix in sight? Thank you for the hard work :)

**Comment by fuzzylogiq** [comment]
I think this should be fixed in https://github.com/ox-it/munki-rebrand/releases/v4.0 with the downside that I couldn't get it working in Python 2 and 3 simultaneously so Python 2 support has been dropped.
