### ISSUE TITLE
MSC App name on Munkitools 5.2

### ISSUE THREAD

**Issue by jstaubr** [ox-it/munki-rebrand#45]
Hello,

the recently released munkitools 5.2 have probably made some changes that prevent renaming the Managed Software Center.app and the app name remains original. Inside the app strings are correctly replaced:
<img width="224" alt="Screenshot 2020-11-25 at 11 27 24" src="https://user-images.githubusercontent.com/20901065/100215421-44ca7300-2f11-11eb-8044-351209b85f7f.png">

Give me a shout If I can provide other info or debug...

**Comment by fuzzylogiq** [comment]
Hi yup I'm aware of the issue and I'm in the process of producing a PR for the main munki code (munki_rebrand is working as intended)

**Comment by Welshdwarf** [comment]
Hello, is it possible to call an old version of MSC in the script ?
 The MUNKIURL
Thanks.

**Comment by jstaubr** [comment]
> Hi yup I'm aware of the issue and I'm in the process of producing a PR for the main munki code (munki_rebrand is working as intended)

Thanks!

**Comment by SilentHunter124** [comment]
Is there a manual workaround we can do if we build munki on our own?

**Comment by fuzzylogiq** [comment]
> Is there a manual workaround we can do if we build munki on our own?

Yes you could build it from my fork (i'll keep it around for now) https://github.com/fuzzylogiq/munki (clone to your computer then run `code/tools/make_munki_mpkg.sh`) then pass that to munki_rebrand.py with the `-k` option

**Comment by jstaubr** [comment]
Hi everyone,
Latest 5.2.1 release fixes the issue for me. 
https://github.com/munki/munki/releases/tag/v5.2.1
