### ISSUE TITLE
Sidebar icons missing

### ISSUE THREAD

**Issue by jonbrown21** [ox-it/munki-rebrand#46]
When running Munki Rebrand without passing a PKG will download the latest release .pkg file and rebrand successfully but after doing so the sidebar icons are gone. 

<img width="211" alt="Screen Shot 2021-01-26 at 2 17 27 PM" src="https://user-images.githubusercontent.com/1732890/105895663-c909a700-5fe3-11eb-972d-395ea95e895f.png">

Posted details in Munki-Rebrand Mac Admins slack area.

**Comment by ahaupt1** [comment]
I was able to work around this by building a new metapackage from munki-source, replacing the following images with the ones I want:

https://github.com/munki/munki/tree/main/code/apps/Managed%20Software%20Center/Managed%20Software%20Center/Assets.xcassets/AppIcon.appiconset
and 
https://github.com/munki/munki/tree/main/code/apps/MunkiStatus/MunkiStatus/Assets.xcassets/AppIcon.appiconset

After that built successfully with all of the assets in the Assets.car file of both apps; I used munki-rebrand to just change the name and sign the resulting package.

**Comment by fuzzylogiq** [comment]
Yes the solution may be to add the assets to the munki_rebrand repo and build the xcassets from that and the custom AppIcon. That is probably what I will attempt to code around anyway.

**Comment by fuzzylogiq** [comment]
Fixed in 4.0RC1, will merge into main after some testing.
