### ISSUE TITLE
Notifications not clickable

### ISSUE THREAD

**Issue by patgmac** [ox-it/munki-rebrand#51]
When getting a branded MSC notification, clicking on it does not open MSC. Presumably because of the name change. Is this something that could possibly be resolved?

**Comment by patgmac** [comment]
Turns out, I saw the same behavior at times with non-branded MSC.

**Comment by bfreezy** [comment]
Pretty sure this is a bug upstream in Munki. Anytime you go to codesign the MSC app (and the bundled munki-notifier app) it breaks the ability for munki-notifier to launch MSC when clicking the "Details" button.
