### ISSUE TITLE
Xcode 13 generates non-editable compiled NIBs

### ISSUE THREAD

**Issue by alx-jones** [ox-it/munki-rebrand#52]
The default build settings in Xcode 13 generates NIBArchives rather than binary Plists. This is touched on in the [Xcode 13 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes).

> Storyboards and XIBs for macOS compile using UINibEncoder to reduce file sizes and improve runtime performance. When deploying an App before macOS 10.13, Xcode generates a backward compatible nib for the older OSes. You can opt out of this behavior by applying the IBC_COMPILER_USE_NIBKEYEDARCHIVER_FOR_MACOS=YES and IBSC_COMPILER_USE_NIBKEYEDARCHIVER_FOR_MACOS=YES user defined overrides in the project’s build setting. (31889616)

This means versions of Munki compiled with Xcode 13 or later cannot be rebranded.

The script fails on line 168 because the file type of the NIB is no longer a binary Plist and so cannot be converted to XML by `plutil`.

`cmd = [PLUTIL, "-convert", "xml1", plist]`

Opting out of this behaviour by setting the two build settings referenced by Apple in the release notes above does fix the problem and generates NIB files that can be edited by munki-rebrand.

**Comment by fuzzylogiq** [comment]
Thanks for bringing this to my attention, which also explains some issues people have been having over in Slack. I will investigate and see if we can work around with a code change

**Comment by fuzzylogiq** [comment]
OK, i'm not convinced the nib rebranding is doing anything anymore since munki moved to Base localization. Can you give https://github.com/ox-it/munki-rebrand/tree/v5.1b1 a try and see if it rebrands as expected in your locale. I tested this switching between en_GB and en and it worked for me.

**Comment by alx-jones** [comment]
Can confirm that works now 👍 

I did notice there wasn't actually anything in those nib files being replaced, so was wondering whether that section was still necessary.

**Comment by patgmac** [comment]
Works for me as well.

**Comment by fuzzylogiq** [comment]
Addressed in https://github.com/ox-it/munki-rebrand/releases/tag/v5.1
