### ISSUE TITLE
code signing as root fails

### ISSUE THREAD

**Issue by Cetartiodactyla** [ox-it/munki-rebrand#58]
While I happily codesign using my user, I’m not able to sucessfully codesign as root. As I need to run munki-rebrand with sudo, codesigning fails. How do I fix this?

**Comment by fuzzylogiq** [comment]
I think this is because you're using one of the newer types of Developer ID certificates and you need to download the G2 one from here: https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer and install it (and the Developer ID cert) into System Keychain (it's not in System Roots)
